contentful/create-contentful-app

lib/index.js
package-lock.json
package.json

As opposed to using a local one with [`file:` option](https://create-react-app.dev/docs/custom-templates/#testing-a-template)
https://github.com/facebook/create-react-app/blob/v3.4.1/packages/create-react-app/createReactApp.js#L750 is the problem. It would parse `@contentful` in our name and break. It's partially also a bug on create-react-app. If a template name has `@` in it's name, it will break. Unless it's part of the organization name.
We already published a template on npm: https://www.npmjs.com/package/@contentful/cra-template-create-contentful-app. 
FYI, this means going forward we will publish 3 times: once for template, for org scoped pkg and create-contentful-app parked name.

fix: Use npm template package

---

template.json
template/src/components/ConfigScreen.spec.tsx
template/src/components/ConfigScreen.tsx

This change is meant to introduce a small example of how `getCurrentState` can be leveraged in `ConfigScreen`.
The main idea here is: there is a way (in v3.18.0) to get a blueprint of the `targetState` which _needs_ to be submitted, unless you want the whole configuration to be reset, and this explains how.

feat: add current state examples

---

package-lock.json
package.json
scripts/deploy.js

This script is meant to automate the current madness we go through to deploy this package. 
Nothing particularly fancy, and probably this cannot be merged before we produce documentation for these steps, but I have just used it for last release and seems to be working. We can get back to it whenever we are rolling out next release

chore: add simple deploy script

---

.circleci/config.yml
.gitignore
scripts/dependency-check/create-manifest-from-template
scripts/dependency-check/create-pull-request
scripts/dependency-check/create-template-from-outdated
scripts/dependency-check/utils.js

This change is mean to provide the capability to update automatically dependencies in `template.json`.
Follows up from #18 
* **not using `init`**
To perform `npm outdated` check we don't need the packages to be installed. Plus, creating a `package.json` from the template is super easy and this saves us a bunch of minutes of CI time
* **multiple dependencies**
As we have agreed, this automation updates all the packages in the `template.json`. We might want to have fine grained control over which dependency gets updated and when.
* **ignored packages**
I have added a list of packages we might want to ignore while performing this check. Currently is empty. Do you think it's something useful?
---
I would like to get your opinion on the points to discuss before proceeding with the rest of the …

chore: [EXT-2124] automate dependecy check

---

scripts/dependency-check/create-pull-request

This is to prevent [this](https://github.com/contentful/create-contentful-app/pull/49):
* find old dependencies;
* create the PR;
* in the attempt to close old PRs it also closes the one just opened

fix: don't auto close PRs

---

template.json

This was confusing people, as the ui-extension-sdk doesn't work
unless run in an iFrame

fix: don't open browser on start

---

template/src/index.tsx

Fixing issue that was raised by #140 
While these styles aren't used directly by the default app template, I think it's worth importing these styles to make it easier for people to use other Forma components.

fix: add forma-36 tokens css import

---

template.json

The script failed on most windows shells. Cross-env ensures that it will
work across platforms.
This was raised in #160

fix: use cross-env in start command

---

template.json

Bumps dependencies in `template.json` with most up to date versions as of today.
<details>
<summary>Test Report</summary>
<pre>
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /test-1606867390/test/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/test-1606867390/test/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-02T00_04_09_287Z-debug.log
</pre>
</details>

chore(deps): daily update 'template.json'

---

.circleci/config.yml

The original intent behind this PR was to also run the tests with node 15 as `npx @contentful/create-contentful-app` was failing there. Unfortunately, the CI currently crashes when running `npx` with node 15, so we cannot actually test that. This might be fixed with node 7.1.0.
But what this PR does include is
- running the basic tests with node 15
- actually testing the local changes in `test-built-app` and not the current latest version on npm

Run tests with node 15

---

lib/index.js

We currently only exit with a non-0 code when the app name is missing.
With this PR we forward the exit codes of create-react-app and also fail with exit code `1` in case of any other error.
This will fix the programmatic use of the package e.g. in our CI.

fix: return correct exit code when init fails

---

.circleci/config.yml

The daily dependency-check job was failing with
```
Error: Cannot find module 'file:/Users/<user>/.npm/_npx/75677/lib/node_modules//package.json'
Require stack:
- /Users/<user>/dev/create-contentful-app/blaaaa/test/node_modules/react-scripts/scripts/init.js
- /Users/<user>/dev/create-contentful-app/blaaaa/test/[eval]
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.resolve (internal/modules/cjs/helpers.js:80:19)
at module.exports (/Users/<user>/dev/create-contentful-app/blaaaa/test/node_modules/react-scripts/scripts/init.js:117:13)
at [eval]:3:14
at Script.runInThisContext (vm.js:120:18)
at Object.runInThisContext (vm.js:309:38)
at Object.<anonymous> ([eval]-wrapper:10:26)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at evalScript …
```

Fix dependency check job

---

template/src/index.tsx

The `sdk` is of type `KnownSDK` and not `BaseExtensionSDK`. Therefore, we might run into type issues in the future.
I removed it which means I can also remove the ugly `as unknown`s.

fix: remove explicit types from init call

---

README.md
package.json

Still doesn't warn when using `npx` though

feat: Clarify supported node/npm versions

---

template.json
template/src/components/ConfigScreen.tsx
template/src/components/Dialog.tsx
template/src/components/EntryEditor.tsx
template/src/components/Field.tsx
template/src/components/Page.tsx
template/src/components/Sidebar.tsx
template/src/index.tsx

Replace `contentful-ui-extensions-sdk` with `@contentful/app-sdk`.
Both packages are identical but the App SDK should be used for apps.

feat: use @contentful/app-sdk

---

lib/index.js

We currently use `.stderr.on('data', [...])` and `.stdout.on('data', [...])` and put the data in `console.log`. That removes color and adds additional new lines
By using `{ stdio: 'inherit' }` we can forward the data directly to stdout.
> Pass through the corresponding stdio stream to/from the parent process. 
That way
- we keep the log color
- we don't add additional empty lines
- the output is prettier and easier to read

feat: directly forward logs from npx process

---

scripts/dependency-check/create-pull-request

We are currently only closing old PRs but do not delete the corresponding branches.
Therefore, we currently have 46 open branches in this repo.
This PR automatically deletes the branch when closing the PR.
Also, the comment is now a regular comment instead of a "review comment". That way the PR now looks the same as if a regular user typed something in the comments box, clicked "Close with comment" and then deleted the branch.

chore: delete branches of old dep-check PRs

---

scripts/dependency-check/create-pull-request

The variable is called `pullRequest` and not `pr` 🙄

chore: typo in #354

---

scripts/dependency-check/create-manifest-from-template
scripts/dependency-check/create-pull-request
scripts/dependency-check/create-template-from-outdated
scripts/dependency-check/utils.js

The parameter is called `issue_number` as we are adding a comment on an issue. 🙄 
To avoid these issues, I added `// @ts-check` to all dep-check scripts to enable typescript.

chore: fix typo & add ts-check

---

.circleci/config.yml
package-lock.json
package.json
scripts/dependency-check/create-pull-request
scripts/dependency-check/merge-pull-request.js
scripts/dependency-check/utils.js

Unfortunately, it is currently not possible to enable the GitHub auto-merge feature via the API (yet). So, we need to do this manually for now. The new script fetches all open PRs, filters them to get the latest dep-check PR, verifies that all checks were successful, squashes that PR and then fetches the latest `master` to the local git. Fetching the latest `master` ensures that the new PR does not contain the same updates as the already merged PR.
It might make sense to run this in a separate job as the final pull might not include the previously merged PR.

chore: auto merge dep-check PRs [EXT-2537]

---

packages/@contentful--app-scripts/README.md
packages/@contentful--app-scripts/bin/app-scripts
packages/@contentful--app-scripts/lib/upload/build-upload-settings.js
packages/@contentful--app-scripts/lib/upload/create-app-bundle.js
packages/@contentful--app-scripts/lib/upload/get-upload-settings-args.js
packages/@contentful--app-scripts/lib/upload/index.js

Activating the upload automatically and add the option `--skip-activation` in non-interactive mode and also adds a prompt to skip activation in interactive mode. 
The documentation was also changed according to the automatic activation.

Feat: scripts activate bundle by default

---

package.json

We expect all versions of the packages to be in sync, which means publishing a change in one package will publish a new version for all packages. 
By default, lerna will always only create a new version for the package that has been changed.
[The option `--force-publish`](https://github.com/lerna/lerna/tree/main/commands/version#--force-publish) will skip the diffing and will create a new version for all packages, if changed or not. 
This will make sure all package versions are in sync. 
Closes #403

fix: always have versions in sync

---

packages/contentful--app-scripts/lib/activate/activate-bundle.js
packages/contentful--app-scripts/lib/activate/activate-bundle.test.js

To activate an app bundle, you need to have at least 1 location present. This sets at least one location (i.e: 'dialog' as it's a default location)

fix: set default location for activating app bundle [EXT-2712]

---

packages/contentful--app-scripts/README.md
packages/contentful--app-scripts/bin/app-scripts
packages/contentful--app-scripts/lib/index.js
packages/contentful--app-scripts/lib/open/index.js
packages/contentful--app-scripts/lib/open/open-settings.js
packages/contentful--app-scripts/lib/open/open-settings.test.js

Adds a simple open command to app-scripts. 
The structure of the call is a bit different as there is no sense to have a interactive/non-interactive mode, as this command will only run in one place and never in a CI. 
So there is only one function executed.

feat: [] adds `open-settings` command to app-scripts

---

packages/contentful--app-scripts/lib/upload/create-app-upload.js
packages/contentful--app-scripts/lib/upload/create-app-upload.test.js
packages/contentful--app-scripts/lib/upload/validate-bundle.js
packages/contentful--app-scripts/lib/upload/validate-bundle.test.js

The upload script will now throw if there is no index.html file, and will warn if there are relative paths.

feat: [EXT-2678] add validation for build folder

---

scripts/dependency-check/utils.js

The package name was changed, removing the `@` from the name, which lead to failing dependency runs, because of still referencing with that prefix.

fix: [] dependency check with correct package name

---

scripts/dependency-check/create-manifest-from-template

With `app-scripts` being part of the `devDependencies` the outdated check should also include the `devDependencies`

fix: [] add dev dependencies to manifest creation

---

scripts/dependency-check/utils.js

It seems like this path was mistakenly changed in a different PR, and we didn't notice as the dependency check script is only run on a timer.

fix: [] incorrect path for dependency check

---

.circleci/config.yml

If you run `npm outdated` before `npm install`, only `dependencies` are displayed as outdated. Only if you run `npm install` also `devDependencies` are listed as outdated.
I didn't find any documentation or a cli flag for this, so I added `npm install` to the CI when updating the `template.json`.
In our case `@contentful/app-scripts` is a few versions behind.

chore: run npm install before checking outdated deps

---

scripts/dependency-check/merge-pull-request.js

The existing logic only merged the `template.json` PRs when all checks were successful. With the new GH action to auto merge dependabot PRs, one check is always `skipped`, because the conditions to run that check do not apply.
With this PR, the template.json PR is also merged when the conclusion is `skipped` or `neutral`.

chore: merge template.json PR with neutral GH check

---

packages/contentful--cra-template-create-contentful-app/template/src/components/Field.spec.tsx

Adding mock for `Fields.spec.ts` as it currently breaks when running `npm start` breaks due to an enforced type check.

fix(tests): ignore typecheck for test which breaks dev-build

---

package-lock.json
packages/contentful--create-contentful-app/lib/index.js
packages/contentful--create-contentful-app/lib/utils.js
packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json

Support template flag for typescript(`--typescript`/`-ts`)  & JS(`--javascript`/`-js`)
Usage: `@contentful/create-contentful-app init my-contentful-app --javascript`

feat(JSTempalte): Support JS templates [EXT-3441]

---

packages/contentful--app-scripts/package.json
packages/contentful--cra-template-create-contentful-app/package.json
packages/contentful--create-contentful-app/package.json
packages/create-contentful-app/package.json

Changelog of `lint-staged` v10:
> From v10.0.0 onwards any new modifications to originally staged files will be automatically added to the commit. If your task previously contained a git add step, please remove this.
Also `*.{js}` causes errors and should be `*.js`

chore: remove `git add` from lint-staged

---

packages/contentful--app-scripts/lib/create-app-definition/create-app-definition.js
packages/contentful--create-contentful-app/src/index.ts

* Update the log message in App Scripts
* Update the log message when using the removed `create-definition` command in CCA (see https://github.com/contentful/apps/pull/788)

fix: change `create-definition` to `create-app-definition`

---

package.json

The packages are currently still all updated at once. Removing `--force-publish`
https://github.com/lerna/lerna/blob/main/commands/version/README.md#--force-publish
> This will skip the lerna changed check for changed packages and forces a package that didn't have a git diff change to be updated.

chore: remove --force-publish

---

package.json

With the current "workaround" we have the issue that the `package-lock.json` files get updated after running `npm install`.
This PR changes the bootstrap logic back to the lerna default as I didn't notice anything being broken with it. 🤞 
This should fix the issue in `master` where we have uncommited changes: https://app.circleci.com/pipelines/github/contentful/create-contentful-app/5083/workflows/8604e124-3148-408c-917b-157d14995040/jobs/17700?invite=true#step-107-13
This issue is originally caused by `lerna` not updating `lockfileVersion` 2 package-lock files correctly. An alternative solution could be patching `lerna` with this PR https://github.com/lerna/lerna/pull/2914, but that feels like too much effort if this simple change can fix things. 🤞

chore: use regular `lerna bootstrap`

---

.github/dependabot.yml
.husky/pre-commit
.npmignore
commitlint.config.js
package-lock.json
package.json
packages/contentful--app-scripts/package.json
packages/contentful--cra-template-create-contentful-app/package.json
packages/contentful--create-contentful-app/package.json
packages/contentful--react-apps-toolkit/package.json
packages/create-contentful-app/package.json

- chore: update dependabot.yml
Allow husky v5+ & do not allow `@types/node` > 17
- chore: upgrade husky to v7
remove commitlint as it has anyway not been used

chore: update dependabot

---

packages/contentful--react-apps-toolkit/src/useCMA.ts

The hook will never return `undefined`

fix: `useCMA()` return value

---

packages/contentful--react-apps-toolkit/src/useFieldValue.spec.ts
packages/contentful--react-apps-toolkit/src/useFieldValue.tsx

Sometimes the value changes when calling `setValue`. With this change, the value is returned when calling `setValue` of `useFieldValue`.

feat: return updated value when setting a field value via `useFieldValue` [EXT-3654]

---

package-lock.json
packages/contentful--react-apps-toolkit/package-lock.json
packages/contentful--react-apps-toolkit/package.json

Required by testing library. I don't know why it currently works, but it is failing in `canary`.
```
Could not auto-detect a React renderer. Are you sure you've installed one of the following
- react-dom
- react-test-renderer
If you are using a bundler, please update your imports to use a specific renderer.
For instructions see: https://react-hooks-testing-library.com/installation#being-specific
```

chore: explicitly add react-test-renderer as dev dependency

---

package-lock.json
packages/contentful--react-apps-toolkit/README.md
packages/contentful--react-apps-toolkit/package.json
packages/contentful--react-apps-toolkit/src/SDKProvider.tsx

BREAKING CHANGE: React Apps Toolkit v1
**React Hooks for building apps faster**
React is the most popular framework when it comes to writing Contentful apps and with the new React Apps Toolkit, we provide multiple new React hooks that abstract the most common use cases. That way, you have to write less boilerplate code and can focus on the core functionality of your Contentful app.  Combined with Contentful’s open source Forma 36 design library it allows developers to seamlessly integrate into Contentful so that you can build editorial apps faster with less manual work. To learn more about the new React Apps Toolkit, check out the [package on npm](https://www.npmjs.com/package/@contentful/react-apps-toolkit).
**Usage:**
```tsx
ReactDOM.render(
// wrap the app with the SDK Provider, so the …
```

feat: React Apps Toolkit v1

---

lerna.json

This should reduce the number of releases.

chore: ignore package-lock.json changes

---

packages/contentful--create-contentful-app/README.md
packages/create-contentful-app/README.md

The screenshot is currently not visible on npm as the image url is relative
-> https://www.npmjs.com/package/create-contentful-app

docs: use absolute screenshot url

---

packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/logger.ts

`err` is of type `unknown` and can therefore also be `undefined`. This e.g. happens when the installation fails. In that case the error is already logged to the console and we reject the promise (https://github.com/contentful/create-contentful-app/blob/6c1f8e278404d7705b2180c96be641fd628e6c35/packages/contentful--create-contentful-app/src/utils.ts#L16). As we stringify `err`, this causes the following output:
With this change, we handle the different types of errors within the `error` function and filter out `undefined`

fix: handle undefined error

---

packages/contentful--create-contentful-app/src/template.ts

To enable also non frontend template we remove the hard check for the app-sdk. 
I thought about adding a pre check to find out if it is a frontend app. But I could not find a reasonable way to find that out, so I decided to just remove it for now

fix: [] remove app-sdk check

---

packages/contentful--app-scripts/lib/upload/create-app-bundle.js
packages/contentful--app-scripts/lib/upload/create-app-upload.js

`userAgentApplication` was added at a point the API could not pick it up, so it has been moved

fix: move userAgentApplication

---

.circleci/config.yml

We cannot use CircleCI user keys anymore for releases (and pushing to github), so we need to use the credentials exposed by vault (GITHUB_TOKEN, GIT_AUTHOR_EMAIL, GIT_AUTHOR_NAME).
I also did some minor refactor removing unused commands and deprecated properties

chore: fix CI

---

lerna.json

Dependabot constantly updates the dependancies of the root and all packages. Each of these updates changes `package.json` and `package-lock.json` files. This makes lerna automatically trigger new releases. For `create-contentful-app` we are now in release 107 where only a dependency, but not the actual code changed.
We do not want to spam npm with new versions. Us triggering a new version triggers dependabot of dependant packages/projects causing noise for our users. We only want to release a new version if something actually changed.
`package-lock.json` is already ignored for lerna. This PR also ignores `package.json`. That way, the changes made by dependabot do not trigger a new lerna release.
(I am not sure whether this is the perfect solution, but it's the best I could come up with …

chore: ignore package.json

---

packages/contentful--app-scripts/lib/utills.test.js
packages/contentful--app-scripts/lib/utils.js
packages/contentful--app-scripts/package.json

Adding new endpoint property `allowNetworks` in the action manifest file.
User should provide the list of allowed networks in action manifest file.
By default the below networks will always have access
`api.contentful.com, upload.contentful.com, 127.0.0.1`

allowNetworks argument added in app action manifest[EXT-4509]

---

packages/contentful--app-scripts/lib/utils.js

Remove unnecessary params. This fails for uploading when the category !== 'Custom'

fix: remove unnecessary params []

---

packages/contentful--create-contentful-app/.mocharc.js
packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/contentful--create-contentful-app/src/includeAppAction.ts
packages/contentful--create-contentful-app/src/includeDeliveryFunction.ts
packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/template.ts
packages/contentful--create-contentful-app/src/types.ts
packages/contentful--create-contentful-app/src/utils.ts
packages/contentful--create-contentful-app/src/utils/file.ts
packages/contentful--create-contentful-app/src/utils/package.ts
packages/contentful--create-contentful-app/test/setup.js
packages/contentful--create-contentful-app/test/utils/file.spec.ts
packages/contentful--create-contentful-app/test/utils/package.spec.ts

The PR includes the following changes
- Adds a new `--delivery-function` option to `create-contentful-app`
- Merges content from `package.json` in delivery function template folder into the project's `package.json`
- Fixes a small bug encountered during testing which prevented the app directory from being removed on an unexpected error

Add --delivery-function option to add the delivery function example to create-contentful-app [MONET-1334]

---

.github/dependabot.yml
package-lock.json
package.json

It seems that the recently released v3.x.x version of `prettier` is [not compatible with](https://github.com/lerna/lerna/issues/3765) the v6.x.x version of `lerna`. 
Due to the breaking changes in `lerna` v7 it seems easier to pin `prettier` on v2.x.x for now and [unblock the pipeline](https://app.circleci.com/pipelines/github/contentful/create-contentful-app/8469/workflows/496e2a08-8677-43e1-a70a-79828e29a1c3/jobs/32104).

chore: downgrade prettier to v2 due to incompatibility with lerna v6

---

.circleci/config.yml
package-lock.json
package.json

BREAKING CHANGE
- deprecate v14 and v16 CI workflows & add v20
- specify v18 in `engines` in package.json

chore: upgrade to node lts (v18) [EXT-4812]

---

.circleci/config.yml
packages/contentful--create-contentful-app/src/getTemplateSource.ts
packages/contentful--create-contentful-app/src/includeAppAction.ts
packages/contentful--create-contentful-app/src/includeDeliveryFunction.ts
packages/contentful--create-contentful-app/src/index.ts

Previously, in order to use `--deliveryFunction` or `--action` option, user needed to specify also `--javascript` or `--typescript` option. If no such option was provided then regular interactive session was started.
After this change `--typescript` option will be automatically assumed. Typescript was chosen because it is already the default template for other options.

feat: assume ts for deliveryFunction if no option provided [MONET-1564]

---

.gitignore

After bootstrapping the project a new folder `.nx` with a bunch of files inside is created. In order to not accidentally commit it I have added it to the `.gitignore` file.

chore: add .nx folder to .gitignore []

---

packages/contentful--create-contentful-app/src/constants.ts
packages/contentful--create-contentful-app/src/getTemplateSource.ts

Because `hosted-app-action-templates` and `hosted-delivery-function-templates` are templates, not examples it was not possible to successfully clone them in case user selected them from examples list. By filtering them out we will avoid confusion when choosing examples from the list.

chore: update the templates list [MONET-1564]

---

packages/contentful--app-scripts/src/organization-api.ts

This fixes an issue where the "Fetching your organizations..." spinner continues to run while the user is selecting from the list of returned organizations.

fix: stop org spinner after fetching organizations

---

packages/contentful--app-scripts/src/utils.test.ts
packages/contentful--app-scripts/src/utils.ts

This PR adds an additional valid event to the `accepts` parameter when defining functions in the `contentful-app-manifest.json` file.

feat: add app event filter to function manifest accepts param [EXT-5079]

---

packages/contentful--app-scripts/src/upload/create-app-upload.ts
packages/contentful--app-scripts/src/upload/validate-bundle.test.ts
packages/contentful--app-scripts/src/upload/validate-bundle.ts
packages/contentful--create-contentful-app/package-lock.json

When the user forgets to run `npm run build` or did not correctly call the `build-functions.js` the CLI still tries to upload the function without any entry file. This results in an error in app-upload-to-delivery which results in a 500 (Internal Server error) response from extensiblity-api.

validate whether the function/action entry points exist in the bundle [MONET-1987]

---

.circleci/config.yml

CI attempts to publish the unscoped `create-contentful-app` directly to npm, but errors with a 429 at npm's API, which we actually suspect to be an auth issue

fix: publish create-contentful-app

---

packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/types.ts

- changes `--function` flag to not require a value. If one is not provided, default to external-references.

fix: cli defaults function flag to external references

---

packages/contentful--app-scripts/src/open/open-settings.ts

This wasn't intended to end up in a release, hence removing it.

fix: remove unnecessary `console.log` statement

---

packages/contentful--app-scripts/README.md
packages/contentful--app-scripts/src/bin.ts
packages/contentful--app-scripts/src/constants.ts
packages/contentful--app-scripts/src/index.ts
packages/contentful--app-scripts/src/install/index.ts
packages/contentful--app-scripts/src/install/install.test.ts
packages/contentful--app-scripts/src/install/install.ts
packages/contentful--app-scripts/src/types.ts

Based on the `open` script, I created a similar `install` script that opens the page where user can specify which space / environment they want the app to be installed to.

Feat: add a script to install the app

---

packages/contentful--app-scripts/src/utils.ts

Extensible Resource Links are introducing two new event types for functions (`resources.search` and `resources.lookup`), and we want the manifest validation to accept these as well.
Ticket: https://contentful.atlassian.net/browse/DANTE-1589

Extend the list of accepted events with ERL events

---

packages/contentful--app-scripts/src/upload/build-upload-settings.test.ts
packages/contentful--app-scripts/src/upload/build-upload-settings.ts
packages/contentful--app-scripts/src/upload/create-app-upload.test.ts

This PR addresses an issue where specifying a host that starts with http:// or https:// causes the upload process to break. 
To fix this, an inquirer filter function has been added to the host prompt in `buildAppUploadSettings`. This function strips out any leading http:// or https:// from the user's input, ensuring that only the base URL is used.

feat: strip protocol from host if provided during upload [EXT-00]

---

packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/create-contentful-app/package-lock.json
packages/create-contentful-app/package.json

Version 1.16.16 of @contentful/create-contentful-app is not available on npm for some reason. While we diagnose the package mirroring issue, we should be able to roll back to this version to get things working again.

fix: use older CCA package that is available on npm []

---

packages/contentful--app-scripts/src/create-app-definition/build-app-definition-settings.test.ts
packages/contentful--app-scripts/src/create-app-definition/build-app-definition-settings.ts
packages/contentful--app-scripts/src/create-app-definition/create-app-definition.ts

When creating an app definition and having the page location selected, you can pass an optional `navigationItem` property which determines whether the page app should appear in the apps dropdown menu and what the name and path for that link should be. This is supported in the Contentful web app when creating and editing an app definition, but it is not supported in our `Create App Definition` script as part of the `@contentful/app-scripts` package. This PR adds this functionality to this script.
I have tested this locally and can confirm that the prompts appear correctly when the page location is selected and that the validations provide warnings correctly. The validations for the link name and path are using the same validations on the input fields in the web app.
Here is the experience …

feat: support setting navigationItem for page in create-app-definition [EXT-5884]

---

packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/contentful--create-contentful-app/src/analytics.ts

create-contentful-app was using a legacy version of the segment analytics node.js package. This PR removes the old package, adds the new one, and makes minor changes according to [this migration guide](https://segment.com/docs/connections/sources/catalog/libraries/server/node/migration/). 
Also see [this PR](https://github.com/contentful/create-contentful-app/pull/1774) for reference, that did the same conversion in the app-scripts package.
This should resolve alert [#107](https://github.com/contentful/create-contentful-app/security/dependabot/107)

chore: migrate to new segment analytics-node package [EXT-5924]

---

packages/contentful--react-apps-toolkit/package-lock.json

Run `npm audit fix` to address vulnerabilities. Specifically, this will resolve [alert #86](https://github.com/contentful/create-contentful-app/security/dependabot/86) as well as vulnerabilities with micromatch and semver packages.

chore: react apps toolkit npm audit fix [EXT-5924]

---

package-lock.json

Run `npm audit fix` at the root. This bumped cross-spawn and a few other changes in the root `package-lock.json`. Change is similar to [this PR](https://github.com/contentful/create-contentful-app/pull/2215/files), which resolves [dependabot security alert](https://github.com/advisories/GHSA-3xgq-45jj-v275) on cross-spawn.

chore: run npm audit fix at root [EXT-5924]

---

packages/create-contentful-app/package-lock.json
packages/create-contentful-app/package.json

Update the `@contentful/create-contentful-app` package in the `create-contentful-app` package to utilize the most recent version. Will resolve this security alert: https://github.com/contentful/create-contentful-app/security/dependabot/107
Also run `npm audit fix` to bump cross-spawn. Change is similar to [this PR](https://github.com/contentful/create-contentful-app/pull/2215/files) and [this PR](https://github.com/contentful/create-contentful-app/pull/2216), which resolves [dependabot security alert](https://github.com/advisories/GHSA-3xgq-45jj-v275) on cross-spawn.

chore: bump contentful-scoped CCA in CCA package [EXT-5924]

---

packages/create-contentful-app/index.js

When using create-contentful-app with node v22, users were seeing a deprecation warning after running `npx create-contentful-app@latest`: 
```
$ npx create-contentful-app@latest
? App name (contentful-app) (node:39520) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```
This deprecation warning is coming from ajv, which is a dependency from eslint. It seems like there is no direct solution for this at the moment, other than suggesting to use node v20 to suppress the warning. 
https://github.com/eslint/eslint/issues/17720
https://github.com/eslint/eslint/issues/17733#issuecomment-2277264699
In the meantime until this is resolved, this PR suppresses warnings so that this is no longer visible to users using node v22 with CCA.

fix: suppress warnings in CCA []

---

packages/contentful--create-contentful-app/src/constants.ts
packages/contentful--create-contentful-app/src/getGithubFolderNames.ts
packages/contentful--create-contentful-app/src/getTemplateSource.ts
packages/contentful--create-contentful-app/src/includeFunction.ts
packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/logger.ts
packages/contentful--create-contentful-app/src/template.ts
packages/contentful--create-contentful-app/src/types.ts
packages/contentful--create-contentful-app/test/getGithubFolderNames.spec.ts
packages/contentful--create-contentful-app/test/getTemplateSource.spec.ts
packages/contentful--create-contentful-app/test/includeFunction.spec.ts

This PR addresses several improvements to error handling for create-contentful-app:
1. **Invalid template error:** Check to see if the template name provided with the `--example` option actually exists as a valid example. If not, then display a more helpful error message directing users where they can find the list.
2. **Invalid function template error:** When the user passes an invalid function template, clean up the error message so the formatting matches the invalid template error. Also, remove the cloned typescript example that is created before the function is created if there is an error.
3. **Error fetching templates:** Add error handling for fetching the example folder names
See below for before and after for these error messages.
| Before | After |
| --- | --- |
| **Invalid …

fix: improve error handling for invalid templates in CCA [EXT-4028]

---

packages/contentful--app-scripts/src/create-app-definition/create-app-definition.test.ts
packages/contentful--app-scripts/src/create-app-definition/create-app-definition.ts

It is now possible for apps to be "frontendless", containing only functions. As such, when creating an app definition, if no frontend locations are specified, the default "src" should be omitted.

fix: only set default src when creating app def if a frontend location is specified [EXT-5935]

---

packages/contentful--app-scripts/README.md
packages/contentful--app-scripts/src/activate/build-bundle-activate-settings.ts
packages/contentful--app-scripts/src/bin.ts
packages/contentful--app-scripts/src/clean-up/build-clean-up-settings.ts
packages/contentful--app-scripts/src/create-app-definition/create-app-definition.test.ts
packages/contentful--app-scripts/src/create-app-definition/create-app-definition.ts
packages/contentful--app-scripts/src/install/install.test.ts
packages/contentful--app-scripts/src/install/install.ts
packages/contentful--app-scripts/src/open/open-settings.test.ts
packages/contentful--app-scripts/src/open/open-settings.ts
packages/contentful--app-scripts/src/types.ts
packages/contentful--app-scripts/src/upload/build-upload-settings.ts
packages/contentful--app-scripts/src/upload/create-app-bundle.ts
packages/contentful--app-scripts/src/utils.test.ts
packages/contentful--app-scripts/src/utils.ts

This PR cleans up handling the `host` option throughout our `app-scripts` package. Here are the specific updates:
- `create-app-definition`: The copy displayed after app definition creation always displayed `app.contentful.com`. Now it will display the correct webapp host based on the host option.
- `upload`: Fixes a bug in interactive mode where the provided host option was not being properly passed through and also updates the copy after success to use the correct webapp host.
- `bundle-cleanup`: Fixes a bug in interactive mode where the provided host option was not being properly passed through.
- `activate`: Fixes a bug in interactive mode where the provided host option was not being properly passed through.
- `open-settings`: Host was not provided as an option, so this adds support …

fix: support host option for all commands [EXT-5971]

---

packages/contentful--app-scripts/src/upsert-actions/get-cli-args.ts

make sure that `manifestFile` has a fallback value in non-interactive mode

fix(app-scripts): set default manifest path in non-interactive mode for upsert-actions

---

packages/contentful--app-scripts/src/generate-function/clone.test.ts
packages/contentful--app-scripts/src/generate-function/clone.ts

There is a small bug in the ```generate-function``` logic where the newest app-manifest entry is altered for the function name. An extraneous './' was included at the start; ```upload``` cannot find the correct build path.
This PR removes the extraneous './'

fix: app-manifest-entry-paths-correction [NONE]

---

packages/contentful--app-scripts/src/bin.ts
packages/contentful--app-scripts/src/generate-function/build-generate-function-settings.test.ts
packages/contentful--app-scripts/src/generate-function/build-generate-function-settings.ts
packages/contentful--app-scripts/src/generate-function/clone.test.ts
packages/contentful--app-scripts/src/generate-function/clone.ts
packages/contentful--app-scripts/src/generate-function/index.ts
packages/contentful--app-scripts/src/types.ts

We are changing how generate-function pulls from the apps repo.
function-example/
├── example1/
│   ├── typescript/
│   ├── javascript/
├── example2/
│   ├── typescript/
│   ├── javascript/
├── example3/
│   ├── typescript/
│   ├── javascript/
Everything is treated the same now, no notion of a ‘example’ vs ‘template’. 
Must specify language, source, and name for each new function.

fix: Simplified input and correct navigation in new structure [EXT-6255]

---

packages/contentful--app-scripts/src/generate-function/build-generate-function-settings.test.ts
packages/contentful--app-scripts/src/generate-function/build-generate-function-settings.ts
packages/contentful--app-scripts/src/generate-function/clone.test.ts
packages/contentful--app-scripts/src/generate-function/clone.ts
packages/contentful--app-scripts/src/generate-function/constants.ts
packages/contentful--app-scripts/src/generate-function/create-function.ts
packages/contentful--app-scripts/src/generate-function/index.ts
packages/contentful--app-scripts/src/generate-function/types.ts

Fix a small bug that adds a duplicate app-manifest to the ```functions``` folder when using ```generate-function```. Also, do early function name validation that will ensure the function can be uploaded.

fix: no duplicate app manifests and better function name validation [EXT-6262]

---

packages/contentful--create-contentful-app/src/index.ts

If someone uses `--javascript` or `--typescript`, they get a _template in that language._ Currently, if they also specify `--function <function-name>`, the function is _always_ typescript. This fixes that - if a user uses the template flag with `--function`, the function is in the language of the template flag.

fix: language-flags-with-function-templates [EXT-6291]

---

packages/contentful--create-contentful-app/src/constants.ts
packages/contentful--create-contentful-app/src/getTemplateSource.ts

Currently, interactive mode automatically filters any examples with 'function' in the name. This fixes that and prevents unnecessary filtering.

fix: filtering examples [EXT-6293]

---

packages/contentful--app-scripts/src/activate/activate-bundle.test.ts
packages/contentful--app-scripts/src/activate/activate-bundle.ts
packages/contentful--app-scripts/src/types.ts
packages/contentful--app-scripts/src/upload/index.ts

There was some default behavior in the `activate` script where the `src` property on a bundle was always being deleted and the `dialog` location was always being added. This makes sense if the app bundle you are uploading contains frontend files. But in order to support bundles with only Contentful functions, we needed to change this behavior. I added checks for whether the bundle has frontend files, and only delete the `src` property and add the `dialog` location if it does. Otherwise, if there is only functions code in the bundle, we should not perform those actions. This then allows the app developer to have both a `src` property (for local development or a third party URL) and a bundle with functions.
If the `activate` is being called from the `upload` script, we already have the …

fix: support bundles without frontend in upload and activate scripts [EXT-6304]

---

package-lock.json
package.json
packages/contentful--app-scripts/src/utils.ts
packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/contentful--create-contentful-app/src/index.ts
packages/contentful--react-apps-toolkit/package-lock.json
packages/contentful--react-apps-toolkit/package.json
packages/contentful--react-apps-toolkit/src/SDKProvider.tsx
packages/create-contentful-app/index.js
packages/create-contentful-app/package-lock.json

The following dependency chain is causing vulnerabilities because inflight is deprecated and unstable:
tiged -> rimraf -> glob -> inflight.
Glob version > 9 deprecates inflight, rimraf version 5 uses glob v10.
Had a [similar change last week](https://github.com/contentful/create-contentful-app/pull/2518), as the issue was occurring in app-scripts. However, since the app-scripts version comes bundled with all the other packages (which had tiged OR rimraf < v5 OR another package in the repo as a dependency) we needed to update all packages in the repo to override rimraf.
In order to allow lerna to release, I made small adjustments to a few comments.

fix: remove child dependency inflight [EXT-6447]

---

packages/contentful--app-scripts/src/utils.ts
packages/contentful--create-contentful-app/src/index.ts
packages/contentful--react-apps-toolkit/src/SDKProvider.tsx
packages/create-contentful-app/index.js

Follow up on [this ticket](https://github.com/contentful/create-contentful-app/pull/2533).
The other releases contain the dependencies of the entire create-contentful-app. This means that the stale version from the linked ticket is not updated in the other releases. So, we need to bump the releases.

fix: rebump all packages [EXT-6447]

---

package-lock.json
package.json
packages/contentful--app-scripts/package-lock.json
packages/contentful--app-scripts/package.json
packages/contentful--app-scripts/src/generate-function/clone.ts
packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/contentful--react-apps-toolkit/package-lock.json
packages/contentful--react-apps-toolkit/package.json
packages/create-contentful-app/index.js
packages/create-contentful-app/package-lock.json
packages/create-contentful-app/package.json

Reverting inflight overwrites because it is messing up the release job.
Revert "fix: remove all references to inflight (#2530)"
This reverts commit a53b6b6fbab4cbfe31fc30020657026be1a4e9d5.
Revert "fix: rebump all packages [EXT-6447] (#2536)"
This reverts commit c7192fd2a390605b3c320f74e0b3f850e241c4ab.
Revert "fix: update create-contentful-app remove inflight (#2533)"
This reverts commit b8a7dd1827507ad68352fd5bef55cb0c47a55f50.
[EXT-6447]: https://contentful.atlassian.net/browse/EXT-6447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: revert inflight overwrites [EXT-6447]

---

packages/contentful--create-contentful-app/README.md
packages/contentful--create-contentful-app/src/analytics.ts
packages/contentful--create-contentful-app/src/getTemplateSource.ts
packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/template.ts
packages/contentful--create-contentful-app/src/types.ts
packages/contentful--create-contentful-app/src/utils.ts
packages/contentful--create-contentful-app/test/utils.spec.ts

**This PR is based on [this one here](https://github.com/contentful/create-contentful-app/pull/2631), and adds a few changes - mostly around how we will detect the fallback package manager.**
This PR adds support for the `--pnpm` CLI option, and [pnpm](https://pnpm.io/) support in general, for the `create-contentful-app` tool. This PR **does not** convert the entire monorepo to use pnpm.
For third party apps using pnpm as a package manage, trying to create Contentful apps with `create-contentful-app` via a custom [npm script](https://docs.npmjs.com/cli/v10/using-npm/scripts) (or any kind of script, really) can end up erroring out when the new app's dependencies are installed because of how different local versions of pnpm and npm are handled.
The commands given in console for installing …

feat: support-pnpm-package-manager [ZEND-6808]

---

packages/contentful--create-contentful-app/README.md
packages/contentful--create-contentful-app/src/analytics.ts
packages/contentful--create-contentful-app/src/getTemplateSource.ts
packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/template.ts
packages/contentful--create-contentful-app/src/types.ts
packages/contentful--create-contentful-app/src/utils.ts
packages/contentful--create-contentful-app/test/utils.spec.ts

This PR adds support for the `--pnpm` CLI option, and [pnpm](https://pnpm.io/) support in general, for the `create-contentful-app` tool. This PR **does not** convert the entire monorepo to use pnpm.
For third party apps using pnpm as a package manager, trying to create Contentful apps with `create-contentful-app` via a custom [npm script](https://docs.npmjs.com/cli/v10/using-npm/scripts) (or any kind of script, really) can end up erroring out when the new app's dependencies are installed because of how different local versions of pnpm and npm are handled.
The commands given in console for installing dependencies, and for creating app definitions, are misleading in this case. There was also some ambiguity and unexpected behavior in the handling of when both `--yarn` and `--npm` flags were …

feat(pnpm): support pnpm as package manager
