contentful/create-contentful-app

.npmignore
package-lock.json
package.json

Added npmignore file to deal with release.

feat: npmignore for release

---

lib/create-app-definition.js
lib/index.js
lib/login.js
lib/prompt-app-definition.js
package-lock.json
package.json

This updates the formatting and copy. I also `tildify` the paths:

chore: formatting & copy updates

---

README.md
package-lock.json
package.json

feat(rename): Remove org prefix

---

lib/create-app-definition.js
lib/prompt-app-definition.js

fix(createDefinition): handle lists and reference fields properly

---

lib/index.js
package.json

With the current setup we aren't able to test local changes to templates. This change aims to make this possible by means of an env variable
> ⚠️ Warning
> This is just a small idea which I tested locally, but might needs some more thought. Scope of this PR is mainly to get some feedback and work a good solution together

chore: introduce local dev mode

---

package-lock.json
package.json

fix(versions): Move all version one higher

---

template.json

Bumps dependencies in `template.json` with most up to date versions as of today.
<details>
<summary>Test Report</summary>
<pre>
> test@0.1.0 test /test-1598400054/test
> react-scripts test
PASS src/components/Dialog.spec.tsx
PASS src/components/Page.spec.tsx
PASS src/components/Field.spec.tsx
PASS src/components/EntryEditor.spec.tsx
PASS src/components/Sidebar.spec.tsx
PASS src/components/ConfigScreen.spec.tsx
Test Suites: 6 passed, 6 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        3.288s
Ran all test suites.
</pre>
</details>

chore(deps): daily update 'template.json'

---

package-lock.json
package.json

Release for: https://github.com/contentful/create-contentful-app/pull/11

feat: Release 0.1.6 with Windows & Linux support

---

package-lock.json
package.json
template.json

bumping ui-ext-sdk version to remove warning errors when developing

Fixing parcel errors

---

package-lock.json
package.json
template/src/components/Field.tsx

Changing this to be consistent with the rest of the template files.

Fixing typo in prop name

---

README.md
template/README.md
template/src/components/Field.tsx

feat: Add links to libraries

---

lib/index.js
package-lock.json
package.json

When errors occur in CRA it's currently hard to tell what's gone wrong. This PR makes it so the stderror and stdout of the CRA process are logged.

feat: log create-react-app output

---

template/public/index.html
template/src/components/LocalhostWarning.tsx
template/src/index.tsx

feat: [EXT-2278] add warning notice page for local development

---

template/README.md

docs: Update README.md

---

package-lock.json
package.json

update the version after https://github.com/contentful/create-contentful-app/pull/366 has been merged

chore: [EXT-2597] Update version of package

---

package.json
packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/create-contentful-app/package-lock.json
packages/create-contentful-app/package.json

The versions of the internally used local packages should always be strict to avoid some side effects of not being in sync with each other

fix: [] use exact version for lerna publish and version

---

.circleci/config.yml
packages/contentful--cra-template-create-contentful-app/template.json
scripts/dependency-check/create-template-from-outdated

Also added the manually updated `template.json` file in the template package

feat: [] run dependency check on canary branch too

---

.github/workflows/dependabot-approve-and-request-merge.yml

Please note: this will run only once merged to `master` because it runs `on: pull_request_target`

chore: automerge dependabot PRs

---

packages/contentful--cra-template-create-contentful-app/template/gitignore
packages/contentful--cra-template-create-contentful-app/template/src/components/ConfigScreen.spec.tsx
packages/contentful--cra-template-create-contentful-app/template/src/components/ConfigScreen.tsx
packages/contentful--cra-template-create-contentful-app/template/src/components/Dialog.spec.tsx
packages/contentful--cra-template-create-contentful-app/template/src/components/EntryEditor.spec.tsx
packages/contentful--cra-template-create-contentful-app/template/src/components/Page.spec.tsx
packages/contentful--cra-template-create-contentful-app/template/src/components/Sidebar.spec.tsx
packages/contentful--cra-template-create-contentful-app/template/src/index.tsx
packages/contentful--cra-template-create-contentful-app/template/src/setupTests.ts
packages/contentful--cra-template-create-contentful-app/template/test/mocks/index.ts
packages/contentful--cra-template-create-contentful-app/template/test/mocks/mockCma.ts

After working on the tasks-app, we found a few improvements that we would like to have in the general template.
Commits:
- feat: change template to have a deeper structure
- feat: configure default testId in template for testing-library
- feat(template): update imports and improve types
- feat(template): enhance gitignore

feat: update template structure []

---

packages/contentful--cra-template-create-contentful-app/template/src/components/ConfigScreen.module.css

We removed the import in https://github.com/contentful/create-contentful-app/pull/754 but not the file itself

fix: remove css file

---

.circleci/config.yml

Forgot to build the packages before the actual release

fix: build before release

---

package-lock.json
packages/contentful--react-apps-toolkit/package-lock.json
packages/contentful--react-apps-toolkit/package.json
packages/contentful--react-apps-toolkit/src/SDKProvider.tsx
packages/contentful--react-apps-toolkit/src/index.spec.ts
packages/contentful--react-apps-toolkit/src/index.ts
packages/contentful--react-apps-toolkit/src/useSDK.spec.ts
packages/contentful--react-apps-toolkit/src/useSDK.ts

Adding the hook and the provider

feat: [EXT-3490] add useSDK hook

---

packages/contentful--react-apps-toolkit/jest.config.js
packages/contentful--react-apps-toolkit/src/SDKProvider.spec.tsx
packages/contentful--react-apps-toolkit/src/SDKProvider.tsx

Adding a timeout to the init function in the SDKProvider

feat: [] add timeout and console warn

---

packages/contentful--react-apps-toolkit/src/index.ts
packages/contentful--react-apps-toolkit/src/useFieldValue.spec.ts
packages/contentful--react-apps-toolkit/src/useFieldValue.tsx

No update to the README as this will be done in another PR

feat: useFieldValue [EXT-3492]

---

packages/contentful--create-contentful-app/package.json
packages/contentful--create-contentful-app/src/index.ts

Each commit is one small isolated change

fix: small fixes/improvements

---

packages/contentful--app-scripts/package-lock.json
packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json

- remove cma.js
- downgrade @types/node to v14
- update other packages
- do not upgrade to ESM only packages (chalk v5)

fix: update dependancies

---

.circleci/config.yml
package-lock.json
package.json
packages/contentful--react-apps-toolkit/package-lock.json

We changed `config.yml` in both `master` & `canary`. So things got a little messy on merge

fix: merge issue in CI config

---

packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/logger.ts
packages/contentful--create-contentful-app/src/template.ts

We're seeing some users having errors downloading with Degit. We're hoping that by logging more information about the errors we should be able to diagnose the problem.

fix: [] log full degit errors

---

packages/contentful--create-contentful-app/src/utils.ts

Address issue https://github.com/contentful/create-contentful-app/issues/1020

fix: run installation inside a shell

---

packages/contentful--react-apps-toolkit/README.md
packages/contentful--react-apps-toolkit/src/useAutoResizer.spec.tsx
packages/contentful--react-apps-toolkit/src/useAutoResizer.tsx

- Adds a React hook to invoke the startAutoResizer/stopAutoResizer functionality.
Credit: @ajeetchaulagain

feat: add useAutoResizer() hook

---

packages/contentful--create-contentful-app/README.md

Add all plain templates to the readme together with the command, to copy-paste and start.

doc: [] add all plain templates to readme

---

.contentful/vault-secrets.yaml

chore: introduce vault [EXT-4076]

---

.circleci/config.yml

chore: use vault secrets [EXT-4076]

---

packages/contentful--app-scripts/lib/clean-up/clean-up-bundles.test.js
packages/contentful--app-scripts/lib/clean-up/get-clean-up-settings.js

- fix: support host parameter in CI
- test: add test cases for custom host and complete bundle fetching

fix: custom host parameter for cleanup [HOMER-1343]

---

packages/contentful--app-scripts/lib/upload/create-app-upload.js
packages/contentful--app-scripts/lib/upload/get-upload-settings-args.js

Added setting for adding the application name to createAppUpload, defaults to `contentful.cli`

feat: add setting of UserAgentApplication for createAppUpload

---

packages/contentful--app-scripts/lib/create-app-definition/build-app-definition-settings.js
packages/contentful--app-scripts/lib/create-app-definition/create-app-definition.js
packages/contentful--create-contentful-app/src/constants.ts
packages/contentful--create-contentful-app/src/index.ts

Suggest creating an App definition right from CLI after bootstrapping an app code.

feat: [EXT-4148] Suggest to create an app definition

---

packages/contentful--create-contentful-app/src/constants.ts
packages/contentful--create-contentful-app/src/getTemplateSource.ts
packages/contentful--create-contentful-app/src/index.ts
packages/contentful--create-contentful-app/src/types.ts
packages/contentful--create-contentful-app/src/utils.ts

Adding templates to the list. Currently templates are: Javascript, Typescript, Vue, Next.js, Vite-React.

feat: [] Separate templates and examples

---

packages/contentful--app-scripts/utils/analytics.js

similiar to https://github.com/contentful/create-contentful-app/pull/1378 let's add the same functionality to app-scripts

fix: [] add noop error handler to app-scripts

---

.github/workflows/dependabot-approve-and-request-merge.yml

chore: [ATOOLS-424] Update dependabot-approve-and-request-merge.yml

---

.circleci/config.yml
.contentful/vault-secrets.yaml

* Use ecosystem bot as this is a open source repo
* Remove GH_TOKEN as that already comes from vault
* Run `vault/configure-lerna`

chore: use ecosystem bot & remove unnecessary config

---

packages/contentful--app-scripts/bin/app-scripts

Fixes the type of the argument for the schema. was expecting a string but got a boolean

fix: [] fix tracking schema violation

---

packages/contentful--create-contentful-app/src/includeAppAction.ts

Now we have build script for both JavaScript and TypeScript templates for hosted actions.

fix: build script for hosted actions[EXT-4509]

---

packages/contentful--app-scripts/lib/upload/create-app-upload.js

Use the host as intended for uploading a zip

fix: host param [EXT-4545]

---

packages/contentful--app-scripts/README.md

Improve commands documentation.

docs: [EXT-4652] Document host param in app scripts

---

packages/contentful--create-contentful-app/src/constants.ts
packages/contentful--create-contentful-app/src/includeAppAction.ts
packages/contentful--create-contentful-app/src/includeDeliveryFunction.ts

Lets clean up unused files that lead to confusion

feat(clean-up): remove unnecessary files after cloning [MONET-1476]

---

packages/contentful--create-contentful-app/src/includeAppAction.ts
packages/contentful--create-contentful-app/src/includeDeliveryFunction.ts

I broke the build script 👀. Filename wont be found as we'll be looking in the wrong place

fix: cleanup broke build script []

---

.circleci/config.yml

Make sure we also test delivery functions and actions before releasing CCA :)

chore: test building delivery functions and actions []

---

packages/contentful--app-scripts/package-lock.json
packages/contentful--app-scripts/package.json
packages/contentful--app-scripts/src/analytics.ts
packages/contentful--create-contentful-app/package-lock.json

upgraded according to https://segment.com/docs/connections/sources/catalog/libraries/server/node/migration
this should fix https://github.com/contentful/create-contentful-app/issues/1773

chore: upgrade analytics-node []

---

.github/workflows/sast.yaml

adding polaris security sast scanning.

feat: adding polaris scanning (sast) security scan

---

package-lock.json
package.json
packages/contentful--app-scripts/package-lock.json
packages/contentful--app-scripts/package.json
packages/contentful--app-scripts/src/create-app-definition/build-app-definition-settings.ts
packages/contentful--app-scripts/src/create-app-definition/create-app-definition.ts
packages/contentful--app-scripts/src/create-app-definition/index.ts
packages/contentful--app-scripts/src/get-management-token.ts
packages/contentful--app-scripts/tsconfig.json

allows EU users to specify the EU version of Contentful's API as the host

feat (@contentful/app-scripts): allow API host overrides when creating app definitions

---

packages/contentful--app-scripts/CHANGELOG.md
packages/contentful--app-scripts/package-lock.json
packages/contentful--app-scripts/package.json
packages/contentful--create-contentful-app/CHANGELOG.md
packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/create-contentful-app/CHANGELOG.md
packages/create-contentful-app/package.json

- @contentful/app-scripts@1.13.3
- @contentful/create-contentful-app@1.11.4
- create-contentful-app@1.2.133

chore(release): release

---

.circleci/config.yml

Setting correct token for release stage

fix: github migration

---

packages/contentful--app-scripts/src/types.ts

Lerna is set to ignore .md files, we need to try a real file.
prettier > types.ts

fix: prettier change on .ts file

---

packages/contentful--create-contentful-app/README.md
packages/create-contentful-app/README.md

Docs: note --function CLI param in README

feat: note --function CLI param in README

---

.circleci/config.yml
packages/contentful--app-scripts/src/utils.ts
packages/contentful--create-contentful-app/README.md
packages/contentful--create-contentful-app/src/includeFunction.ts

- Adds values to create ts/js examples of appevent handlers and transformation functions
- Some formatting fixes

feat: Support for handler and transformer functions [EXT-5139] [EXT-5133]

---

package-lock.json
package.json
packages/contentful--app-scripts/src/activate/index.ts
packages/contentful--app-scripts/src/bin.ts
packages/contentful--app-scripts/src/feedback/feedback.ts
packages/contentful--app-scripts/src/feedback/index.ts
packages/contentful--app-scripts/src/index.ts
packages/contentful--app-scripts/src/upload/index.ts

Adds feedback command `feedback` as well as a nudge on upload and activate commands to collect dev feedback

feat: adding cli feedback link + nudge

---

packages/contentful--app-scripts/src/utils.ts

Follow-up to https://github.com/contentful/create-contentful-app/pull/2101
- The previous PR did not work since the lerna config is also ignoring `.md` files. 🤦‍♀️ 
- No editing a comment to trigger a new version.

feat: adds a period in order to trigger new version [CFISO-1832]

---

packages/contentful--app-scripts/src/utils.ts

Follow up to #2198, we need to edit a file in the package to trigger the new release/version.

fix: edit comment to trigger new version []

---

packages/contentful--create-contentful-app/package-lock.json
packages/contentful--create-contentful-app/package.json
packages/contentful--create-contentful-app/src/index.ts

Bump `app-scripts` package in the `@contentful/create-contentful-app` package. Also edited a comment to force a new version release for this package.

fix: bump app-scripts in contentful-scoped cca package []

---

packages/contentful--app-scripts/src/definition-api.ts

In the interactive experience for the `upload` script in the `app-scripts` package, we allow users to select from a list of app definitions in their organization. A single Contentful organization can create a maximum of 250 app definitions, and we are currently not paginating this request, so we are only getting the first 100 definitions. This was evident when I was trying to select an app definition from a list in an organization that had over 100 definitions and I did not see it as an option to select. This PR batches the requests for app definitions so that we can display all of the app definitions for an organization.
**Before (only first 100 visible, A-L**):
**After (all definitions in the org are visible, A-Z):**

fix: batch requests to get app definitions in upload script []

---

.circleci/config.yml
packages/contentful--app-scripts/README.md
packages/contentful--app-scripts/package-lock.json
packages/contentful--app-scripts/package.json
packages/contentful--app-scripts/src/bin.ts
packages/contentful--app-scripts/src/build-functions/__tests__/build-functions.test.ts
packages/contentful--app-scripts/src/build-functions/__tests__/contentful-app-manifest.json
packages/contentful--app-scripts/src/build-functions/__tests__/esbuild.config.js
packages/contentful--app-scripts/src/build-functions/__tests__/fixtures/another-contentful-app-manifest.json
packages/contentful--app-scripts/src/build-functions/__tests__/fixtures/function.ts
packages/contentful--app-scripts/src/build-functions/build-functions.ts
packages/contentful--app-scripts/src/build-functions/index.ts
packages/contentful--app-scripts/src/build-functions/prompt-build-functions-options.ts
packages/contentful--app-scripts/src/constants.ts
packages/contentful--app-scripts/src/create-app-definition/build-app-parameter-settings.ts
packages/contentful--app-scripts/src/index.ts
packages/contentful--app-scripts/src/types.ts
packages/contentful--app-scripts/tsconfig.json

adds a `build-functions` script to `contentful-app-scripts` to build Typescript, or non-standard Javascript, source code for Contentful Functions into an App Framework compatible bundle

feat: build-functions app script [EXT-5978]

---

packages/contentful--app-scripts/src/generate-function/clone.test.ts
packages/contentful--app-scripts/src/generate-function/clone.ts

fix: Removed unneeded './' at start of entry path and entry entryFile

---

packages/contentful--app-scripts/src/bin.ts
packages/contentful--app-scripts/src/generate-function/build-generate-function-settings.test.ts
packages/contentful--app-scripts/src/generate-function/build-generate-function-settings.ts
packages/contentful--app-scripts/src/generate-function/clone.test.ts
packages/contentful--app-scripts/src/generate-function/clone.ts
packages/contentful--app-scripts/src/generate-function/index.ts
packages/contentful--app-scripts/src/types.ts

See [2368](https://github.com/contentful/create-contentful-app/pull/2368)

fix: Simplified input and correct navigation in new structure [EXT-6255]

---

packages/contentful--app-scripts/src/add-locations/add-locations.test.ts
packages/contentful--app-scripts/src/add-locations/add-locations.ts
packages/contentful--app-scripts/src/add-locations/build-add-locations-settings.test.ts
packages/contentful--app-scripts/src/add-locations/build-add-locations-settings.ts
packages/contentful--app-scripts/src/add-locations/index.ts
packages/contentful--app-scripts/src/bin.ts
packages/contentful--app-scripts/src/create-app-definition/build-app-definition-settings.ts
packages/contentful--app-scripts/src/create-app-definition/create-app-definition.ts
packages/contentful--app-scripts/src/create-type-safe-locations.test.ts
packages/contentful--app-scripts/src/create-type-safe-locations.ts
packages/contentful--app-scripts/src/definition-api.ts
packages/contentful--app-scripts/src/index.ts
packages/contentful--app-scripts/src/location-prompts.ts
packages/contentful--app-scripts/src/types.ts

Add locations script [EXT-6267]

---

packages/contentful--create-contentful-app/src/constants.ts

Fix for https://github.com/contentful/create-contentful-app/pull/2416

fix: remove-haa-templates-from-ignored []

---

packages/contentful--app-scripts/src/upload/create-app-bundle.test.ts
packages/contentful--app-scripts/src/upload/create-app-bundle.ts

- Removes references to App Functions being in Beta

feat: remove reference to App Functions in Beta [EXT-6270]

---

packages/create-contentful-app/index.js
packages/create-contentful-app/package-lock.json
packages/create-contentful-app/package.json

Follow up to this PR [here](https://github.com/contentful/create-contentful-app/pull/2530)

fix: update create-contentful-app remove inflight [EXT-6447]
